version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
    - ./backend/.env
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
    - ./backend:/app
    ports:
    - "8000:8000"
    depends_on:
    - db

  frontend:
    image: node:20
    working_dir: /app
    env_file:
      - ./frontend/.env
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
    - ./frontend:/app
    ports:
    - "5173:5173"

volumes:
  db_data: