# Generated by Django 5.2.6 on 2025-10-06 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('details_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('requires_payment_method', 'requires_payment_method'), ('processing', 'processing'), ('succeeded', 'succeeded'), ('canceled', 'canceled')], default='processing', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.sellerprofile')),
            ],
        ),
    ]
